### PR TITLE
Fix crash when quickly adding/removing tabs in switcher

### LINKED ISSUE #2757: [Bug] Swiping to close tab and quickly clicking new tab causes crash
DuckDuckGo Version: 7.115.0.4
iOS: 17.4.1 (21E236)
Model: iPhone 11 Pro

When swiping to close a tab and quickly tapping the plus to open a new tab, DuckDuckGo crashes 

https://github.com/duckduckgo/iOS/assets/80120827/23c33829-e50e-4cf7-b13a-d16dc854a020

### PR DESCRIPTION
**Pull request by dus7**
Task/Issue URL: https://app.asana.com/0/414235014887631/1204624719960838/f
Tech Design URL:
CC:

**Description**:

This PR prevents internal inconsistency during CollectionView updates by not allowing to add a tab to model during batch updates execution block.

**Steps to test this PR**:
1. Go to Tab Switcher
2. Make sure there are at least two tabs
3. Drag tab to delete and immediately try to add a new tab
4. Attempt similar scenario with keyboard shortcuts (cmd+n)

—
###### Internal references:
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)

### CODE REVIEW

File: DuckDuckGo/TabViewCell.swift [hunk 1]
```diff
@@ -123,12 +123,12 @@ class TabViewCell: UICollectionViewCell {
     }
 
     private func startRemoveAnimation() {
+        self.isDeleting = true
+        self.deleteTab()
```
Comment (dus7) [inline DuckDuckGo/TabViewCell.swift:127]: This allows for shorter delay before adding a tab is again possible. Based on my checks it does not interfere with animations. Once this function is called, the gesture is committed anyway.

**Review by aataraxiaa — APPROVED** [review]
Tested and LGTM 🚀
